# Supabase CLI configuration for READ THE ROOM
project_id = "read-the-room"

[api]
enabled = true

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]
jwt_expiry = 3600
enable_signup = true